name: Gatsby Publish

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ dev ]

jobs:
  build:
    env:
      GATSBY_ALGOLIA_APP_ID:      ${{ secrets.GATSBY_ALGOLIA_APP_ID}}
      ALGOLIA_ADMIN_KEY:          ${{ secrets.ALGOLIA_ADMIN_KEY}}
      GATSBY_ALGOLIA_SEARCH_KEY:  ${{ secrets.GATSBY_ALGOLIA_SEARCH_KEY}}
      
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: enriikke/gatsby-gh-pages-action@v2.1.1
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}